ControleVisita/Models/VisitaViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Security.Claims;
using System.Threading.Tasks;
using System.Web;
using ApiConsorcioNet.Extensoes;
using OracleContext;
using Dapper;
using System.Globalization;

namespace ControleVisita.Models
{
    public class VisitaViewModel
    {
        public static List<VisitaModel> Get(int codgrupo, string empresa)
        {
            //new LoginData().GetUser().Empresa
            using (var db = new OracleDataContext(ApiConsorcioNet.Conexao.ConnectionStrings.Acesso(empresa)))
            {
                // var user = (LoginModel)HttpContext.Current.Session["USERMODEL"];

                var response = db.PCURSORVISITA(codgrupo, null, null)
                    .Select(m => new VisitaModel
                    {
                        Id = m.CODVISITA.GetValueOrDefault(),
                        Cliente = new PessoaModel
                        {
                            NomeCompleto = m.VISITADO,
                            DddCelular = string.IsNullOrEmpty(m.CELULAR) ? m.CELULAR.Substring(0, 2) : "",
                            Celular = m.CELULAR,
                            Telefone = m.FONE,
                            WhatsApp = m.WHATSAPP,
                            Email = m.EMAIL,
                            Atividade = m.ATIVIDADE,
                            Endereco = new EnderecoModel
                            {

                                Logradouro = m.ENDERECO,
                                UF = m.UF,
                                Cidade = m.CIDADE
                            }
                        },
                        ValorBem = m.VALORBEM,
                        ValorBemAux = m.VALORBEM != null ? m.VALORBEM.Value.ToString("N2") : "",
                        DataVisita = m.DATAVISITA,
                        IsVendaRealizada = m.VENDEU == "1",
                        MotivoNaoVenda = m.MOTIVONAOVENDA,
                        BemViewModel = new BemViewModel
                        {
                            Modelo = m.MODELOBEM,
                            Marca = m.MARCABEM
                        },
                        Agendamento = new AgendaModel
                        {
                            DataAgendamento = m.DATAREAGENDAMENTO,

                        },
                        HistoricoVisita = m.OBSERVACOES,
                        Usuario = m.USUARIOATUALIZACAO,
                        DataInclusao = m.DATAINCLUSAO.GetValueOrDefault()

                    });

                return response.ToList();

            }
        }

        public VisitaModel GetVisita(int codvisita, string empresa)
        {
            using (var db = new OracleDataContext(ApiConsorcioNet.Conexao.ConnectionStrings.Acesso(empresa)))
            {
                var response = db.CNVISITAs.Where(a => a.CODVISITA == codvisita).ToList()
                    .Select(t => new VisitaModel
                    {
                        Id = t.CODVISITA,
                        CodGrupo = t.CODGRUPO.ToString(),
                        IdPessoa = t.IDPESSOA == null ? 0 : Convert.ToInt32(t.IDPESSOA),
                        Cliente = new PessoaModel
                        {
                            NomeCompleto = t.VISITADO,
                            DDDFone = t.DDDFONE,
                            Telefone = t.FONE,
                            Email = t.EMAIL,
                            DddCelular = t.DDDCELULAR,
                            Celular = t.CELULAR,
                            WhatsApp = t.WHATSAPP,
                            Atividade = t.ATIVIDADE,
                            IdPessoa = t.IDPESSOA == null ? 0 : Convert.ToInt32(t.IDPESSOA),


                            Endereco = new EnderecoModel
                            {
                                UF = t.UF,
                                Cep = "",
                                Cidade = t.CIDADE,
                                Logradouro = t.ENDERECO
                            }

                        },

                        BemViewModel = new BemViewModel
                        {
                            Modelo = t.MODELOBEM,
                            Marca = t.MARCABEM
                        },
                        ValorBemAux = t.VALORBEM != null ? t.VALORBEM.Value.ToString("N2") : "",
                        ValorBem = t.VALORBEM,
                        MotivoNaoVenda = t.MOTIVONAOVENDA,

                        Agendamento = new AgendaModel
                        {
                            DataAgendamento = t.DATAREAGENDAMENTO,
                            InformacaoAgendamento = t.OBSERVACOES,

                        },
                        HistoricoVisita = t.OBSERVACOES,
                        Usuario = t.USUARIOATUALIZACAO,
                        IsVendaRealizada = t.VENDEU == "1",
                        DataVisita = t.DATAVISITA,
                        DataInclusao = t.DATAINCLUSAO.GetValueOrDefault(),
                        MotivoVisita = t.MOTIVOVISITA,
                        Percepcao = t.PERCEPCAO



                    }).ToList();

                return response.FirstOrDefault();
            }
        }

        public IEnumerable<VisitaHistoricoModel> GetHistoricoVisita(int codvisita, int idpessoa, string empresa)
        {
            using (var db = new Oracle.ManagedDataAccess.Client.OracleConnection(ApiConsorcioNet.Conexao.ConnectionStrings.AcessoOracleODP(empresa)))
            {
                var query = @"SELECT DISTINCT VW.* FROM (
                            select T.DATA_VISITA,
                                            T.OBSERVACOES,
                                            T.MOTIVOVISITA,
                                            T.PERCEPCAO,
                                            T.DATA_REAGENDAMENTO,
                                            T.USUARIOINCLUSAO,
                                            T.MOTIVO_NAO_VENDA,
                                            T.MARCABEM,
                                            T.MODELOBEM,
                                            T.VALORBEM
                              from CN_VISITAS T
                              where t.codvisita = :CODVISITA and t.DTAEXCLUSAO IS NULL
                              union all 
                              select T.DATA_VISITA,
                                            T.OBSERVACOES,
                                            T.MOTIVOVISITA,
                                            T.PERCEPCAO,
                                            T.DATA_REAGENDAMENTO,
                                            T.USUARIOINCLUSAO,
                                            T.MOTIVO_NAO_VENDA,
                                            T.MARCABEM,
                                            T.MODELOBEM,
                                            T.VALORBEM
                              from CN_VISITAS T  
                             where t.idpessoa = :IDPESSOA AND t.DTAEXCLUSAO IS NULL
                             order by DATA_VISITA desc) VW";


                var response = db.Query(query, new { CODVISITA = codvisita, IDPESSOA = idpessoa });

                List<VisitaHistoricoModel> historicoModels = new List<VisitaHistoricoModel>();
                foreach (var item in response)
                {
                    var visita = new VisitaHistoricoModel();

                    visita.DataVisita = item.DATA_VISITA;
                    visita.HistoricoVisita = item.OBSERVACOES;
                    visita.MotivoVisita = item.MOTIVOVISITA;
                    visita.Percepcao = item.PERCEPCAO;
                    visita.Usuario = item.USUARIOINCLUSAO;
                    visita.MotivoNaoVenda = item.MOTIVO_NAO_VENDA;
                    visita.BemViewModel = new BemViewModel { ValorBem = Convert.ToDecimal(item.VALORBEM), Marca = item.MARCABEM, Modelo = item.MODELOBEM };

                    visita.ValorBem = Convert.ToDecimal(item.VALORBEM);
                    visita.ValorBemAux = string.Format(CultureInfo.GetCultureInfo("pt-BR"), "{0:C}", visita.ValorBem);


                    visita.Agendamento = new AgendaModel
                    {
                        DataAgendamento = item.DATA_REAGENDAMENTO
                    };

                    historicoModels.Add(visita);

                }

                return historicoModels.OrderByDescending(a => a.DataVisita).ToList();
            }
        }

        public static IEnumerable<VisitaModel> GetVisitas(decimal codgrupo, string empresa, FiltroModelView filtro)
        {

            using (var db = new Oracle.ManagedDataAccess.Client.OracleConnection(ApiConsorcioNet.Conexao.ConnectionStrings.AcessoOracleODP(empresa)))
            {
                Dapper.Oracle.OracleDynamicParameters param = new Dapper.Oracle.OracleDynamicParameters();

                var vcursor = @"    select distinct CODVISITA,
                                           COD_GRUPO,
                                            DATA_VISITA,
                                            NOMECOMPLETO AS VISITADO,
                                           TELEFONE as FONE,
                                          logradouro as ENDERECO,
                                           VENDEU,
                                            MOTIVO_NAO_VENDA,
                                            OBSERVACOES,
                                            DATA_REAGENDAMENTO,
                                            DATA_ATUALIZACAO,
                                            USUARIO_ATUALIZACAO,
                                            REAGENDAMENTO_REALIZADO,
                                            EMAIL,
                                            VALORBEM,
                                            MARCABEM,
                                            MODELOBEM,

ControleVisita/Controllers/VisitaController.cs
using System;
using System.Collections.Generic;
using System.Dynamic;
using System.Globalization;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using System.Web.Mvc;
using ApiConsorcioNet.Extensoes;
using ControleVisita.Models;
using ControleVisita.Models.IdentityExtensions;

namespace ControleVisita.Controllers
{

    [Authorize]
    public class VisitaController : Controller
    {
        VisitaViewModel visita = new VisitaViewModel();
        // GET: Visita
        public ActionResult Index()
        {
            return View();
        }


        public ActionResult Cadastrar()
        {
            // ViewBag.Clientes = await Models.ClienteData.Get();
            var visita = new VisitaModel();

            ViewData["HISTORICOVISITA"] = new List<VisitaHistoricoModel>();

            if (Request.QueryString["p"] != null)
            {
                int codvisita = Convert.ToInt32(Request.QueryString["p"]);
                var v = new VisitaViewModel().GetVisita(codvisita, User.Identity.GetEmpresa());

                visita.IdPessoa = v.IdPessoa;
                visita.BemViewModel = v.BemViewModel;
                visita.ValorBem = v.ValorBem;
                visita.ValorBemAux = v.ValorBemAux;
                visita.MotivoVisita = v.MotivoVisita;


                ViewData["HISTORICOVISITA"] = new VisitaViewModel().GetHistoricoVisita(codvisita, visita.IdPessoa, User.Identity.GetEmpresa());

                ViewData["DADOS_CLIENTE"] = ClienteData.Get(v.IdPessoa, User.Identity.GetEmpresa()).Result;

            }


            ViewBag.Motivos = ToSelectList(MotivoViewModel.GetAll());
            ViewBag.Estados = CidadeModel.ToSectList(CidadeModel.GetEstado());



            return View(visita);
        }



        [ValidateAntiForgeryToken]
        [HttpPost]
        public ActionResult Cadastrar(VisitaModel model)
        {

          

            if (model.IdPessoa == 0)
            {
                ModelState.AddModelError(Guid.NewGuid().ToString(), "Selecione um cliente");
                return View(model);
            }

            if (model.Venda == "Não Realizada" && string.IsNullOrEmpty(model.MotivoNaoVenda))
            {
                ModelState.AddModelError(Guid.NewGuid().ToString(), "Selecione um motivo da não venda");
                return View(model);
            }


            model.Cliente = ClienteData.Get(model.IdPessoa, User.Identity.GetEmpresa()).Result;

            if (ModelState.IsValid)
            {
                var user = (LoginModel)Session["USUARIOLOGADO"];


                model.ValorBem = CorrigiValorMoeda(model.ValorBemAux);
                model.ValorVenda = CorrigiValorMoeda(model.ValorVendaStr);


                VisitaViewModel.AddOrUpdate(model, user);

                ViewBag.Error = model.Id == 0 ? "0|success" : "Cadastro Atualizado com sucesso|success";

                //ViewData["HISTORICOVISITA"] = new VisitaViewModel().GetHistoricoVisita(Convert.ToInt32(model.Id), model.Cliente.IdPessoa, User.Identity.GetEmpresa());

                return View(new VisitaModel());
            }


            ViewData["HISTORICOVISITA"] = new VisitaViewModel();
            ViewBag.Error = "1|error";

            return View(model);
        }
        private decimal CorrigiValorMoeda(string valor)
        {
            if (string.IsNullOrEmpty(valor))
                return 0;

            var remove = valor.Replace(".", "").Replace(",", ".");
            var value = Decimal.Parse(remove, CultureInfo.InvariantCulture);
            return value;
        }

        [NonAction]
        public SelectList ToSelectList(IEnumerable<MotivoModel> dados)
        {
            List<SelectListItem> list = new List<SelectListItem>();


            foreach (var row in dados)
            {
                list.Add(new SelectListItem()
                {
                    Text = row.Motivo,
                    Value = row.IdMotivo.ToString()
                });
            }

            return new SelectList(list, "Value", "Text");
        }

        public async Task<ActionResult> ListaVisita()
        {
            var listaView = new List<VisitaModel>();
            var request = Request.QueryString["clickhome"];

            if (!string.IsNullOrEmpty(request))
            {
                listaView = (List<VisitaModel>)await visita.GetNextVisita(User.Identity.Getcodgrupo(), User.Identity.GetEmpresa());
            }

            return View(listaView.OrderByDescending(a => a.DataVisita).ToList());
        }


        //[HttpPost]
        //public ActionResult ListaVisita(DateTime datainicial, DateTime datafinal, bool isVendaRealizada)
        //{


        //    var response = VisitaViewModel
        //        .Get(User.Identity.Getcodgrupo(), datainicial, datafinal)
        //        .WhereIf(isVendaRealizada, model => model.IsVendaRealizada)
        //        .ToList()
        //        .OrderByDescending(a => a.DataVisita);

        //    ViewBag.TitlePesquisa = $"Período {datainicial.Date:dd/MM/yyyy} até {datafinal:dd/MM/yyyy}";


        //    return View(response);
        //}

        [HttpPost]
        public ActionResult ListaVisita(FiltroModelView filtro)
        {


            var response = VisitaViewModel
                .GetVisitas(User.Identity.Getcodgrupo(), User.Identity.GetEmpresa(), filtro)
                .ToList()
                .OrderByDescending(a => a.DataVisita);


            //  ViewBag.TitlePesquisa = $"Período {datainicial.Date:dd/MM/yyyy} até {datafinal:dd/MM/yyyy}";

            return View(response);
        }

        public ActionResult Agenda()
        {
            return View();
        }

        [HttpGet]
        public PartialViewResult Historico(int idpessoa)
        {
            ViewData["DADOS_CLIENTE"] = ClienteData.Get(idpessoa, User.Identity.GetEmpresa());

            ViewData["HISTORICOVISITA"] = new VisitaViewModel().GetHistoricoVisita(0, idpessoa, User.Identity.GetEmpresa());
            return PartialView("_Historico");
        }

        public ActionResult TransferenciaLead()
        {
            return View();
        }


    }
}

ControleVisita/Views/Visita/GridVisita.cshtml
@using ControleVisita.Models.IdentityExtensions
@{
    ViewBag.Title = "ListaVisita";
    //ViewBag.TitlePesquisa = "";
}



<script src="https://cdnjs.cloudflare.com/ajax/libs/exceljs/3.3.1/exceljs.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/FileSaver.js/1.3.8/FileSaver.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/babel-polyfill/7.4.0/polyfill.min.js"></script>




<div id="gridVisita" class="row">
    @(Html.DevExtreme().DataGrid<ControleVisita.Models.VisitaModel>()
        .DataSource(ds=>ds.WebApi().Controller("VisitaApi")
            .LoadAction("Get")
            .LoadParams(new{usuario = @User.Identity.GetUsuario(),empresa=User.Identity.GetEmpresa()})
            .LoadMode(DataSourceLoadMode.Raw)
            .DeleteAction("Delete").Key("Id")
          
        )

        .NoDataText("Nenhuma visita cadastrada")
        .LoadPanel(m => m.Enabled(true))
        .RowAlternationEnabled(true)
        .Export(e => e.Enabled(true).AllowExportSelectedData(false))
        .OnExporting("exporting")
        .FilterRow(f => f.Visible(true))
        .HeaderFilter(f => f.Visible(true))
        .ColumnHidingEnabled(true)
        .ColumnChooser(c => c.Enabled(true))

        .Columns(columns =>
        {

            columns.Add().Caption("").CellTemplate(@<text>

                                                       <a href="@Url.Action("Cadastrar", "Visita")?p=<%= data.Id%>" class="dx-icon-edit"></a>

                                                    </text>).VisibleIndex(0).Width(50);
            columns.AddFor(m => m.Id).Visible(true).AllowEditing(false).Width(80).VisibleIndex(0);
            columns.AddFor(m => m.Usuario).GroupIndex(0).VisibleIndex(1);
            columns.AddFor(m => m.DataVisita).DataType(GridColumnDataType.Date).Width(100)
                .Format("dd/MM/yyyy").AllowResizing(true).SortOrder(SortOrder.Desc).VisibleIndex(3);
            columns.AddFor(m => m.Cliente.NomeCompleto).Caption("Cliente").VisibleIndex(4);
            columns.AddFor(m => m.Cliente.NroCelularCompleto).Visible(false).VisibleIndex(5);
            columns.AddFor(m => m.Cliente.DddCelular).Visible(false).VisibleIndex(6);
            columns.AddFor(m => m.Cliente.Celular).Visible(false).VisibleIndex(7);
            columns.AddFor(m => m.Cliente.Email).Caption("E-mail").Visible(false).VisibleIndex(8);
            columns.AddFor(m => m.VendaRealizadaStr).Caption("Venda Realizada").VisibleIndex(9).Width(100);
            columns.AddFor(m => m.Cliente.Telefone).Caption("Telefone").Visible(false).VisibleIndex(10);
            columns.AddFor(m => m.Cliente.Endereco.UF).Caption("Estado").Visible(false).VisibleIndex(11);
            columns.AddFor(m => m.Cliente.Endereco.Cidade).Caption("Cidade").Visible(false).VisibleIndex(12);
            columns.AddFor(m => m.Cliente.Endereco.Logradouro).Caption("Logradouro").Visible(false).VisibleIndex(13);

            columns.AddFor(m => m.MotivoNaoVenda)
                .Lookup(l => l.DataSource(w => w.WebApi().Controller("MotivoApi")
                    .LoadAction("Get")
                    .LoadMode(DataSourceLoadMode.Raw)
                    .Key("Motivo")
                    ).ValueExpr("Motivo")
                    .DisplayExpr("Motivo")

                ).VisibleIndex(14);




            columns.AddFor(m => m.Agendamento.DataAgendamento).VisibleIndex(14)
                .Caption("Data Reagendamento").DataType(GridColumnDataType.Date).Format("dd/MM/yyyy").Width(100);



            columns.AddFor(m => m.BemViewModel.Marca).Visible(false).VisibleIndex(15);
            columns.AddFor(m => m.BemViewModel.Modelo).Visible(false).VisibleIndex(16);


            columns.AddFor(m => m.ValorBem).VisibleIndex(17).Name("vlr_bem").CssClass("money").CalculateCellValue(@<text>

                                                                                                                      function(data){
                                                                                                                      return  [data.ValorBem].toLocaleString('pt-br', { minimumFractionDigits: 2 })
                                                                                                                      }

                                                                                                                   </text>);
            // columns.AddFor(m => m.Cliente.DddCelular);
            // columns.AddFor(m => m.Cliente.Celular);
            columns.AddFor(m => m.Cliente.WhatsApp).Visible(false);
            columns.AddFor(m => m.HistoricoVisita);

            columns.AddFor(m => m.Cliente.Atividade).Visible(false);

        })
        .ShowBorders(true)

        .Editing(e => e
            .AllowAdding(false)
            .AllowUpdating(false)
            .AllowDeleting(true)
            .Mode(GridEditMode.Popup)
            .UseIcons(true)
            .Form(f=>f.Items(items =>
            {


                items.AddGroup()
                    .Caption("Dados do Cliente")
                    .Items(g =>
                    {
                        g.AddSimpleFor(m => m.Cliente.NomeCompleto);
                        g.AddSimpleFor(m => m.Cliente.DddCelular).Editor(editor => editor.TextBox().Mask("00"));
                        g.AddSimpleFor(m => m.Cliente.Celular).Editor(editor => editor.TextBox().Mask("00000-0000"));

                        g.AddSimpleFor(m => m.Cliente.DDDFone);
                        g.AddSimpleFor(m => m.Cliente.Telefone);
                        g.AddSimpleFor(m => m.Cliente.WhatsApp).ColSpan(4);

                        g.AddSimpleFor(m => m.Cliente.Endereco.UF)
                            .Editor(editor=>editor.SelectBox().DataSource(ds=>ds.WebApi()
                                .Controller("UFApi")
                                .LoadAction("GetUF")
                                .LoadMode(DataSourceLoadMode.Raw)
                                .CacheRawData(true)
                                .Key("ID"))
                                .DisplayExpr("NOME")
                                .ValueExpr("NOME")
                                .SearchEnabled(true)
                                .OnSelectionChanged("Cidade")
                                // .OnValueChanged("Cidade")
                                .ID("dxUF"));

                        g.AddSimpleFor(m => m.Cliente.Endereco.Cidade)
                            .Editor(editor => editor.Lookup().DataSource(ds => ds.WebApi()
                                .Controller("CidadeApi")
                                .LoadAction("GetCidade")
                                .Key("NOME")
                                .LoadMode(DataSourceLoadMode.Raw)
                                .CacheRawData(true)
                                )
                                .DisplayExpr("NOME")
                                .ValueExpr("NOME")
                                .SearchEnabled(true)
                                .ID("dxCidade"));

                        g.AddSimpleFor(m => m.Cliente.Endereco.Logradouro);


                    });

                items.AddGroup()
                    .Caption("Dados da Visita")
                    .ColCount(1)
                    .ColSpan(2)
                    .Items(g =>
                    {
                        g.AddSimpleFor(m => m.Id).Editor(editor=>editor.TextBox());
                        g.AddSimpleFor(m => m.DataVisita).Editor(editor => editor.DateBox().Max(DateTime.Now));
                        g.AddSimpleFor(m => m.VendaRealizadaStr).Editor(editor=>editor.TextBox());
                        g.AddSimpleFor(m => m.Agendamento.DataAgendamento).Editor(editor => editor.DateBox());
                        g.AddSimpleFor(m => m.MotivoNaoVenda).Editor(editor => editor.SelectBox()
                            .DataSource(ds => ds.WebApi()
                                .Controller("MotivoApi").LoadAction("Get").Key("Motivo")
                                .LoadMode(DataSourceLoadMode.Raw)
                            )

                            .ValueExpr("Motivo")
                            .DisplayExpr("Motivo")
                            .OnValueChanged("onchangeMotivo")
                            .ShowClearButton(true)
                            .Placeholder("Selecione o Motivo"))
                            ;


                        g.AddSimpleFor(m => m.BemViewModel.Marca)
                            .Editor(editor => editor.SelectBox().DataSource(ds => ds.WebApi().RouteName("selectbox")
                                .LoadAction("GetBems").Key("Marca")
                                .LoadParams(new {empresa = @User.Identity.GetEmpresa()})
                                .LoadMode(DataSourceLoadMode.Raw)
                                ).DisplayExpr("Marca")
                                .ValueExpr("Marca")

                                .Placeholder("Selecione o marca"));

                        g.AddSimpleFor(m => m.BemViewModel.Modelo);
                        g.AddSimpleFor(m => m.ValorBem);


                        g.AddSimpleFor(m => m.HistoricoVisita)
                            .ColSpan(6)
                            .Editor(editor => editor.TextArea().Height(100).Width(300));

                    });

            }))

        )
        .SortByGroupSummaryInfo(i => i.Add().SummaryItem("count"))
        .Summary(s=>s.TotalItems(items =>
        {
            items.AddFor(m => m.Id).SummaryType(SummaryType.Count)
                .DisplayFormat("Total: {0}");



        })))
</div>



<script>

    $(document).ready(function() {

        $('.money').mask('000.000.000.000.000,00', { reverse: true});
        });

        function FormataCurrency(e) {
            return e.toLocaleString('pt-br', { minimumFractionDigits: 2 });
    }

    function onchangeMotivo(e) {


        if (e.value === "SEM INTERESSE") {
            $("#Agendamento_DataAgendamento").prop('required', false);
            $("#HistoricoVisita").prop('required', false);
        }
        else if (e.value === "COMPARANDO COM A CONCORRÊNCIA") {
            $("#Agendamento_DataAgendamento").prop('required', true);
        }

        else if (e.value === "AVALIANDO PROPOSTA") {
            $("#Agendamento_DataAgendamento").prop('required', true);
        }
        else if (e.value === "SOLICITOU CONTATO FUTURO") {
            $("#Agendamento_DataAgendamento").prop('required', true);
        }
        else if (e.value === "NÃO ATENDEU") {
            $("#Agendamento_DataAgendamento").prop('required', true);
        }
        else if (e.value === "OUTROS") {
            $("#Agendamento_DataAgendamento").prop('required', true);
            $("#HistoricoVisita").prop('required', true);
        }
        else if (e.value === "OUTROS") {
            $("#Agendamento_DataAgendamento").prop('required', true);
            $("#HistoricoVisita").prop('required', true);
        }

        else if (e.value === "OUTROS") {
            $("#Agendamento_DataAgendamento").prop('required', true);
            $("#HistoricoVisita").prop('required', true);
        }

        else if (e.value === "JÁ TEM COTA DE OUTRA ADMINISTRADORA") {
            $("#Agendamento_DataAgendamento").prop('required', false);
            $("#HistoricoVisita").prop('required', true);

        } else {
            $("#Agendamento_DataAgendamento").prop('required', false);
            $("#HistoricoVisita").prop('required', false);


        }

    }


    function Cidade(e) {

       console.log(e);

        $("#dxCidade").dxSelectBox("instance").getDataSource().filter(["ESTADO", "=", e.value]);
        $("#dxCidade").dxSelectBox("instance").getDataSource().reload();
    }

    function exporting(e) {
        var workbook = new ExcelJS.Workbook();
        var worksheet = workbook.addWorksheet('Visita');

        DevExpress.excelExporter.exportDataGrid({
            component: e.component,
            worksheet: worksheet,
            autoFilterEnabled: true
        }).then(function() {
            // https://github.com/exceljs/exceljs#writing-xlsx
            workbook.xlsx.writeBuffer().then(function(buffer) {
                saveAs(new Blob([buffer], { type: 'application/octet-stream' }), 'Visitas.xlsx');
            });
        });
        e.cancel = true;
    }

    function sendRequest(url, method, data) {
        var d = $.Deferred();

        method = method || "GET";

        $.ajax(url,
            {
            method: method,
                data: data,
                cache: false,
                xhrFields: { withCredentials: true }
        }).then(function(result) {
            d.resolve(method === "GET" ? result.data : result);
        },
            function(xhr) {
            d.reject(xhr.responseJSON ? xhr.responseJSON.Message : xhr.statusText);
        });

        return d.promise();
    }

    function OnRowUpdating(e) {

        console.log(e);
        @*var url = '@Url.Action("Cadastrar","Visita")?idvisita=' + e.key.ID;

        window.location(url);*@
      sendRequest('../api/VisitaApi/?id=' + e.key.Id + "&empresa=" + '@User.Identity.GetEmpresa()' + "&codgrupo="+'@User.Identity.Getcodgrupo()'+"&login="+'@User.Identity.GetUsuario()', "PUT", { key: e.key, values: JSON.stringify(e.newData) });
    }

    function OnRowRemoving(e) {

        console.log(e.key.Id);
        sendRequest('../api/VisitaApi/?id=' + e.key.Id+'&usuario=@User.Identity.GetUsuario()'+'&empresa=@User.Identity.GetEmpresa()', "DELETE", { key: e.key, values: JSON.stringify(e.newData) });

    }


</script>

ControleVisita/Views/Visita/Index.cshtml
@model ControleVisita.Models.VisitaModel

@{
    ViewBag.Title = "Index";
}


<h2>Index</h2>